export const teammates = [
  {
    id: 1,
    name: "AHMET",
    team: "WEB TEAM",
    position: "TEAM LEAD",
    contact: "10 YIL",
  },
  {
    id: 2,
    name: "FILIZ",
    team: "WEB TEAM",
    position: "SR PRODUCT OWNER",
    contact: "5 YIL",
  },
  {
    id: 3,
    name: "NUMAN",
    team: "WEB TEAM",
    position: "SOFTWARE DEVELOPER",
    contact: "5 YIL",
  },
  {
    id: 4,
    name: "MUSTAFA",
    team: "WEB TEAM",
    position: "SOFTWARE DEVELOPER",
    contact: "5 YIL",
  },
  {
    id: 5,
    name: "TULAY",
    team: "WEB TEAM",
    position: "SOFTWARE DEVELOPER",
    contact: "2 YIL",
  },
  {
    id: 6,
    name: "AYDIN",
    team: "WEB TEAM",
    position: "SR SOFTWARE DEVELOPER",
    contact: "8 AY",
  },
  {
    id: 7,
    name: "BURCU",
    team: "WEB TEAM",
    position: "DEVELOPER IN TEST",
    contact: "2 YIL",
  },
  {
    id: 8,
    name: "BURAY",
    team: "WEB TEAM",
    position: "SOFTWARE DEVELOPER",
    contact: "2 YIL",
  },
  {
    id: 9,
    name: "SERHAT",
    team: "WEB TEAM",
    position: "SR SOFTWARE DEVELOPER",
    contact: "8 AY",
  },
  {
    id: 10,
    name: "MUZAFFER",
    team: "WEB TEAM",
    position: "DEVELOPER IN TEST",
    contact: "3+ YIL",
  },
  {
    id: 11,
    name: "SERENAY",
    team: "WEB TEAM",
    position: "SOFTWARE DEVELOPER",
    contact: "2 YIL",
  },
  {
    id: 12,
    name: "YUNUS",
    team: "WEB TEAM",
    position: "SR SOFTWARE DEVELOPER",
    contact: "8 YIL",
  },
  {
    id: 13,
    name: "OZGE",
    team: "WEB TEAM",
    position: "DEVELOPER IN TEST",
    contact: "3+ YIL",
  },
  {
    id: 14,
    name: "ASLI",
    team: "WEB TEAM",
    position: "SOFTWARE DEVELOPER",
    contact: "2 YIL",
  },
  {
    id: 15,
    name: "KUTLU",
    team: "MOBILE WEB TEAM",
    position: "TEAM LEAD",
    contact: "10 YIL",
  },
  {
    id: 16,
    name: "MURAT",
    team: "MOBILE WEB TEAM",
    position: "SR PRODUCT OWNER",
    contact: "8 YIL",
  },
  {
    id: 17,
    name: "ISMAIL",
    team: "MOBILE WEB TEAM",
    position: "SOFTWARE DEVELOPER",
    contact: "5 YIL",
  },
  {
    id: 18,
    name: "FATIH",
    team: "MOBILE WEB TEAM",
    position: "SR SOFTWARE DEVELOPER",
    contact: "8 AY",
  },
  {
    id: 19,
    name: "ERDEM",
    team: "MOBILE WEB TEAM",
    position: "SOFTWARE DEVELOPER",
    contact: "2 YIL",
  },
  {
    id: 20,
    name: "GIZEM",
    team: "MOBILE WEB TEAM",
    position: "SR SOFTWARE DEVELOPER",
    contact: "8 YA",
  },
  {
    id: 21,
    name: "DINCER",
    team: "MOBILE WEB TEAM",
    position: "DEVELOPER IN TEST",
    contact: "3+ YIL",
  },
  {
    id: 22,
    name: "YIGIT",
    team: "MOBILE WEB TEAM",
    position: "SOFTWARE DEVELOPER",
    contact: "3+ YIL",
  },
  {
    id: 23,
    name: "TARIK",
    team: "MOBILE WEB TEAM",
    position: "SR SOFTWARE DEVELOPER",
    contact: "8 AY",
  },
  {
    id: 24,
    name: "ALI",
    team: "MOBILE WEB TEAM",
    position: "DEVELOPER IN TEST",
    contact: "3+ YIL",
  },
  {
    id: 25,
    name: "MERVE",
    team: "MOBILE WEB TEAM",
    position: "SOFTWARE DEVELOPER",
    contact: "2 YIL",
  },
  {
    id: 26,
    name: "HUSEIN",
    team: "MOBILE WEB TEAM",
    position: "SR SOFTWARE DEVELOPER",
    contact: "8 AY",
  },
  {
    id: 27,
    name: "ERCAN",
    team: "MOBILE WEB TEAM",
    position: "DEVELOPER IN TEST",
    contact: "3+ YIL",
  },
  {
    id: 28,
    name: "VEYSEL",
    team: "MOBILE WEB TEAM",
    position: "SOFTWARE DEVELOPER",
    contact: "2 YIL",
  },
];
